### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by Iegoshi** [nikiroo/fanfix#2]
How would you install this? I don't see any native app/ installer.

**Comment by nikiroo** [comment]
Well, I would download the JAR file and execute it. No installation required.
It needs Java 6 (or Java 7 or Java 8) i you don't already have it (see also EXE wrapper below for specific help on Windows).

By the way, if you are not yet used to the program, you may also want to check [fanfix-swing](https://github.com/nikiroo/fanfix-swing/releases/).
It makes use of this project, is thus 100% compatible and looks a bit better I think (when finalized, it will be the main graphical project for fanfix).
But it's still a beta version... I think it should be out of beta in a couple of weeks.

Still, if by any chance you are on Windows, I can also point you to [fanfix-swing EXE wrapper](https://github.com/nikiroo/fanfix-swing/raw/master/fanfix-swing.exe).

How to use it:
- download it (obviously :))
- ALSO download fanfix (this project) or fanfix-swing (the beta version) JAR file
- rename the JAR file into **fanfix-swing** (without the version -- but of course do not change the **.jar** extension)
  - for example: if you have **fanfix-swing-0.0.1**, rename it into **fanfix-swing**
  - for example: if you have **fanfix-3.2.1** rename it into **fanfix-swing** (yes, you need the "-swing" part in the name for the wrapper)
- double-click on the EXE file (the one that should have an icon)

(If you don't have Java, the wrapper will help you find it.)

And, of course... do not hesitate and tell me if you have difficulties (including which OS you use if possible).

PS: you actually point something interesting; I should probably document a bit how to run the program for those that are not used to JAR files (and maybe some notes about Windows that always warns you about any new program you try to run).
Well. I add it to my TODO list then.

Regards,

**Comment by nikiroo** [comment]
ok, well, it went quicker than estimated.

You can find the latest graphical version here: https://github.com/nikiroo/fanfix-swing/releases
The EXE included is a standalone program (you run it, it works, no JAR required).

This one (Fanfix, as opposed to Fanfix-Swing) will be slowly changed into a command-line only program.

Regards,
Niki

**Comment by nikiroo** [comment]
Ok, the new version at https://github.com/nikiroo/fanfix-swing/releases now has everything this one used to have.
Plus an EXE for Windows (even if the JAR file actually works on Windows, too).

So I close this ticket.
If you have more questions, feel free to ask.
